title: Azriel Stephen's Portfolio
description: This is my personal portfolio website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://azriel-stephen.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-cayman
